package alum_profe;

import SistemaInscripciones.Conexion;
import SistemaInscripciones.LoginAdministrador;
import static SistemaInscripciones.LoginAdministrador.PASSWD;
import static SistemaInscripciones.LoginAdministrador.URL;
import static SistemaInscripciones.LoginAdministrador.USERNAME;
import static SistemaInscripciones.LoginAdministrador.User;
import SistemaInscripciones.UIMenuAlumno;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alvaz
 */
public class Consulta extends javax.swing.JFrame {
    public static final String URL = "jdbc:postgresql://localhost:5432/proyecto_inscripciones";
    public static final String USERNAME = "equipo";
    public static final String PASSWD = "equipo2021**";
    PreparedStatement prepared;
    ResultSet result;
    /**
     * Creates new form Consulta
     */
    public Consulta() {
        initComponents();
        
        LoginAdministrador alumno = new LoginAdministrador();
        jlCuenta.setText(LoginAdministrador.User);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbRegresar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jBConsultar = new javax.swing.JButton();
        jlCuenta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbRegresar.setText("Regresar");
        jbRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegresarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel8.setText(" Consulta de Inscripción");

        JTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(JTable);

        jLabel1.setText("Número de cuenta:");

        jBConsultar.setText("Consultar");
        jBConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarActionPerformed(evt);
            }
        });

        jlCuenta.setText("                             ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbRegresar)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jlCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBConsultar)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jBConsultar)
                    .addComponent(jlCuenta))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbRegresar))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegresarActionPerformed
        // TODO add your handling code here:
        UIMenuAlumno jfUIMenuAlumno = new UIMenuAlumno(); //Nombre de la clase, nombre de la variable = new Nombre de la Clase ();
        jfUIMenuAlumno.setSize(270, 160); //Al objeto le asignamos un tamaño (de ventana).
        jfUIMenuAlumno.pack(); //Para que se centre la ventana.
        jfUIMenuAlumno.setLocationRelativeTo(null); //
        jfUIMenuAlumno.setVisible(true); //Para hcaer a la ventana visible.
        this.setVisible(false); 
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jbRegresarActionPerformed

    private void jBConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Asignatura");
        modelo.addColumn("Periodo");
        modelo.addColumn("Cupo");
        modelo.addColumn("Profesor");
        modelo.addColumn("Dia");
        modelo.addColumn("Hora inicio");
        modelo.addColumn("Hora fin");
        modelo.addColumn("Salon");
        
        JTable.setModel(modelo);
        
        String datos[] = new String[8];
        
        Connection conexion = null;
        
        try {
            Conexion.conexion = Conexion.getConnection();
            prepared = Conexion.conexion.prepareStatement("SELECT alum_num_cuenta, asig_nombre, peri_id_periodo,grup_cupo, pers_nombre || ' ' || pers_apaterno AS profesor, dia_nombre, hora_ini, hora_fin, salo_id_salon \n" +
                "FROM inscripcion \n" +
                "INNER JOIN grupo ON inscripcion.grup_id_grupo=grupo.grup_id_grupo\n" +
                "INNER JOIN alumno ON inscripcion.alum_id_alumno=alumno.alum_id_alumno\n" +
                "INNER JOIN Horario ON grupo.grup_id_grupo=horario.grup_id_grupo \n" +
                "INNER JOIN Hora ON Hora.hora_id_hora=Horario.hora_id_hora \n" +
                "INNER JOIN Dia ON Horario.dia_id_dia=Dia.dia_id_dia \n" +
                "INNER JOIN Profesor ON grupo.prof_id_profesor=profesor.prof_id_profesor\n" +
                "INNER JOIN persona ON profesor.pers_id_persona=persona.pers_id_persona\n" +
                "INNER JOIN asignatura ON asignatura.asig_id_asignatura=grupo.asig_id_asignatura\n" +
                "WHERE alum_num_cuenta=?;");
            prepared.setString(1, User);
            result = prepared.executeQuery();
            
            while (result.next()){
                //jtfNombreAsignatura.setText(result.getString("asig_id_asignatura"));

                datos[0] = result.getString("asig_nombre");
                datos[1] = result.getString("peri_id_periodo");
                datos[2] = result.getString("grup_cupo");
                datos[3] = result.getString("profesor");
                datos[4] = result.getString("dia_nombre");
                datos[5] = result.getString("hora_ini");
                datos[6] = result.getString("hora_fin");
                datos[7] = result.getString("salo_id_salon");
                
                modelo.addRow(datos);

            }
            
            Conexion.conexion.close();
        } catch (Exception e) {
            System.err.println("Error: " + e);
        }
        

    }//GEN-LAST:event_jBConsultarActionPerformed
    
    public Connection getConnection () {
        Connection conexion = null;
        
        try {
            Class.forName("org.postgresql.Driver");
            conexion = DriverManager.getConnection(URL, USERNAME, PASSWD);
            //JOptionPane.showMessageDialog(null,"conexion exitosa");
        } catch (Exception e){
            System.err.println("error" + e);
        }
            
        return conexion;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTable;
    private javax.swing.JButton jBConsultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbRegresar;
    private javax.swing.JLabel jlCuenta;
    // End of variables declaration//GEN-END:variables

}